import Foundation

public struct FunFact: Equatable, Hashable, Sendable {
    public let text: String
    public let symbolName: String
    public let paletteIndex: Int

    public init(text: String, symbolName: String, paletteIndex: Int) {
        self.text = text
        self.symbolName = symbolName
        self.paletteIndex = paletteIndex
    }
}

public extension FunFact {
    static let defaultFacts: [FunFact] = [
        FunFact(text: "A day on Venus is longer than its year.", symbolName: "sparkles", paletteIndex: 0),
        FunFact(text: "Octopuses have blue blood and three hearts.", symbolName: "drop.fill", paletteIndex: 1),
        FunFact(text: "Bananas are berries, but strawberries are not.", symbolName: "leaf.fill", paletteIndex: 2),
        FunFact(text: "Honey never spoils when it is sealed well.", symbolName: "hexagon.fill", paletteIndex: 3),
        FunFact(text: "Sharks are older than trees by about 50 million years.", symbolName: "wave.3.right", paletteIndex: 4),
        FunFact(text: "The Eiffel Tower can grow taller on hot days.", symbolName: "thermometer.sun.fill", paletteIndex: 5),
        FunFact(text: "Space smells faintly like seared steak to astronauts.", symbolName: "moon.stars.fill", paletteIndex: 0),
        FunFact(text: "A cloud can weigh more than a million pounds.", symbolName: "cloud.fill", paletteIndex: 1),
        FunFact(text: "Wombat cubes are nature's strangest geometry flex.", symbolName: "cube.fill", paletteIndex: 2),
        FunFact(text: "The first computer bug was an actual moth.", symbolName: "cpu.fill", paletteIndex: 3),
        FunFact(text: "There are more possible chess games than atoms in Earth.", symbolName: "checkerboard.rectangle", paletteIndex: 4),
        FunFact(text: "Your bones are about five times stronger than steel by weight.", symbolName: "figure.walk", paletteIndex: 5),
        FunFact(text: "A teaspoon of neutron star matter would weigh billions of tons.", symbolName: "atom", paletteIndex: 0),
        FunFact(text: "The Moon is slowly drifting away from Earth.", symbolName: "circle.lefthalf.filled", paletteIndex: 1),
        FunFact(text: "Some metals explode when they touch water.", symbolName: "bolt.fill", paletteIndex: 2),
        FunFact(text: "The shortest war in history lasted under an hour.", symbolName: "timer", paletteIndex: 3),
        FunFact(text: "A group of flamingos is called a flamboyance.", symbolName: "paintpalette.fill", paletteIndex: 4),
        FunFact(text: "The human nose can remember around 50,000 scents.", symbolName: "wind", paletteIndex: 5),
        FunFact(text: "Saturn would float in water if you had a big enough bathtub.", symbolName: "circle.grid.cross.fill", paletteIndex: 0),
        FunFact(text: "The dot over a lowercase i is called a tittle.", symbolName: "textformat", paletteIndex: 1),
        FunFact(text: "Some turtles can breathe through their back end.", symbolName: "bubble.left.and.bubble.right.fill", paletteIndex: 2),
        FunFact(text: "The first oranges were probably green.", symbolName: "circle.fill", paletteIndex: 3),
        FunFact(text: "A bolt of lightning is hotter than the Sun's surface.", symbolName: "cloud.bolt.fill", paletteIndex: 4),
        FunFact(text: "Most of the oxygen you breathe comes from ocean plankton.", symbolName: "water.waves", paletteIndex: 5),
        FunFact(text: "The word laser began as an acronym.", symbolName: "laser.burst", paletteIndex: 0),
        FunFact(text: "Some diamonds rain down inside Neptune and Uranus.", symbolName: "diamond.fill", paletteIndex: 1),
        FunFact(text: "Your brain uses about 20 percent of your body's energy.", symbolName: "brain.head.profile", paletteIndex: 2),
        FunFact(text: "The first alarm clock could ring only at 4 a.m.", symbolName: "alarm.fill", paletteIndex: 3),
        FunFact(text: "Hot water can freeze faster than cold water in some conditions.", symbolName: "snowflake", paletteIndex: 4),
        FunFact(text: "A single strand of spider silk can be tougher than steel.", symbolName: "line.diagonal", paletteIndex: 5),
        FunFact(text: "The Pacific Ocean is wider than the Moon.", symbolName: "globe.americas.fill", paletteIndex: 0),
        FunFact(text: "Some sea slugs can photosynthesize after eating algae.", symbolName: "sun.max.fill", paletteIndex: 1),
        FunFact(text: "The inventor of the Frisbee was turned into one after death.", symbolName: "circle.dashed", paletteIndex: 2),
        FunFact(text: "The fingerprints of koalas are oddly human-like.", symbolName: "touchid", paletteIndex: 3),
        FunFact(text: "Sound travels about four times faster in water than in air.", symbolName: "speaker.wave.3.fill", paletteIndex: 4),
        FunFact(text: "A day on Mercury lasts about 59 Earth days.", symbolName: "smallcircle.filled.circle.fill", paletteIndex: 5),
        FunFact(text: "The smell after rain is called petrichor.", symbolName: "cloud.rain.fill", paletteIndex: 0),
        FunFact(text: "The longest hiccuping spell lasted for decades.", symbolName: "waveform.path.ecg", paletteIndex: 1),
        FunFact(text: "The first email was sent in 1971.", symbolName: "paperplane.fill", paletteIndex: 2),
        FunFact(text: "Gold is edible, but your lunch deserves better.", symbolName: "seal.fill", paletteIndex: 3),
        FunFact(text: "The Sun makes up more than 99 percent of the solar system's mass.", symbolName: "sun.max.circle.fill", paletteIndex: 4),
        FunFact(text: "A jiffy is a real unit of time in physics.", symbolName: "clock.badge.checkmark", paletteIndex: 5),
        FunFact(text: "The first webcam watched a coffee pot.", symbolName: "camera.fill", paletteIndex: 0),
        FunFact(text: "You can hear rhubarb grow in the right conditions.", symbolName: "ear.fill", paletteIndex: 1),
        FunFact(text: "The North Pole has no permanent time zone.", symbolName: "location.north.circle.fill", paletteIndex: 2),
        FunFact(text: "Glass is made mostly from sand.", symbolName: "hourglass", paletteIndex: 3),
        FunFact(text: "A hummingbird's heart can beat over 1,000 times per minute.", symbolName: "heart.fill", paletteIndex: 4),
        FunFact(text: "The universe has no known center.", symbolName: "scope", paletteIndex: 5),
        FunFact(text: "Cleopatra lived closer to the iPhone than to the pyramids.", symbolName: "hourglass", paletteIndex: 0),
        FunFact(text: "The first iPhone launched without an App Store.", symbolName: "paperplane.fill", paletteIndex: 1),
        FunFact(text: "A single Google search can use thousands of computers.", symbolName: "cpu.fill", paletteIndex: 2),
        FunFact(text: "The first 1 GB hard drive weighed over 500 pounds.", symbolName: "externaldrive.fill", paletteIndex: 3),
        FunFact(text: "The word robot comes from a Czech word for forced labor.", symbolName: "gearshape.fill", paletteIndex: 4),
        FunFact(text: "The QWERTY keyboard layout is over 150 years old.", symbolName: "keyboard.fill", paletteIndex: 5),
        FunFact(text: "The first text message said Merry Christmas.", symbolName: "message.fill", paletteIndex: 0),
        FunFact(text: "Wi-Fi does not officially stand for Wireless Fidelity.", symbolName: "wifi", paletteIndex: 1),
        FunFact(text: "Bluetooth is named after a 10th-century king.", symbolName: "dot.radiowaves.left.and.right", paletteIndex: 2),
        FunFact(text: "The first YouTube video was filmed at a zoo.", symbolName: "play.rectangle.fill", paletteIndex: 3),
        FunFact(text: "The first domain ever registered was symbolics.com.", symbolName: "globe.americas.fill", paletteIndex: 4),
        FunFact(text: "The @ symbol is centuries older than email.", symbolName: "at", paletteIndex: 5),
        FunFact(text: "The first computer mouse was made of wood.", symbolName: "computermouse.fill", paletteIndex: 0),
        FunFact(text: "A byte is usually eight bits.", symbolName: "number.square.fill", paletteIndex: 1),
        FunFact(text: "The first known algorithm was written long before computers.", symbolName: "function", paletteIndex: 2),
        FunFact(text: "QR codes were invented to track car parts.", symbolName: "qrcode", paletteIndex: 3),
        FunFact(text: "The Apollo guidance computer had less memory than a calculator.", symbolName: "moon.stars.fill", paletteIndex: 4),
        FunFact(text: "The first website is still online.", symbolName: "network", paletteIndex: 5),
        FunFact(text: "The term debugging became famous after a real insect incident.", symbolName: "ladybug.fill", paletteIndex: 0),
        FunFact(text: "The first portable computer weighed about 24 pounds.", symbolName: "laptopcomputer", paletteIndex: 1),
        FunFact(text: "The first emoji set had only 176 icons.", symbolName: "face.smiling.fill", paletteIndex: 2),
        FunFact(text: "Unicode can represent over a million code points.", symbolName: "textformat", paletteIndex: 3),
        FunFact(text: "The first barcode scan bought a pack of gum.", symbolName: "barcode.viewfinder", paletteIndex: 4),
        FunFact(text: "The first video game patent was filed in 1947.", symbolName: "gamecontroller.fill", paletteIndex: 5),
        FunFact(text: "The PlayStation began as a Nintendo collaboration.", symbolName: "gamecontroller.fill", paletteIndex: 0),
        FunFact(text: "The first camera photo needed hours of exposure.", symbolName: "camera.fill", paletteIndex: 1),
        FunFact(text: "The first color photo was made in 1861.", symbolName: "paintpalette.fill", paletteIndex: 2),
        FunFact(text: "Movie film usually runs at 24 frames per second.", symbolName: "film.fill", paletteIndex: 3),
        FunFact(text: "The first feature-length animated film was from Argentina.", symbolName: "wand.and.stars", paletteIndex: 4),
        FunFact(text: "The shortest commercial flight can last under two minutes.", symbolName: "airplane", paletteIndex: 5),
        FunFact(text: "The world's first speeding ticket was for 8 mph.", symbolName: "speedometer", paletteIndex: 0),
        FunFact(text: "The first subway opened in London in 1863.", symbolName: "tram.fill", paletteIndex: 1),
        FunFact(text: "The Golden Gate Bridge is painted International Orange.", symbolName: "paintbrush.fill", paletteIndex: 2),
        FunFact(text: "The Statue of Liberty was once copper-colored.", symbolName: "flame.fill", paletteIndex: 3),
        FunFact(text: "The Leaning Tower of Pisa took nearly 200 years to build.", symbolName: "building.columns.fill", paletteIndex: 4),
        FunFact(text: "The Great Wall is not visible from the Moon by eye.", symbolName: "eye.fill", paletteIndex: 5),
        FunFact(text: "Vatican City is the smallest country by area.", symbolName: "mappin.circle.fill", paletteIndex: 0),
        FunFact(text: "Canada has more lakes than any other country.", symbolName: "water.waves", paletteIndex: 1),
        FunFact(text: "Russia spans 11 time zones.", symbolName: "clock.fill", paletteIndex: 2),
        FunFact(text: "The Sahara is larger than the continental United States.", symbolName: "sun.max.fill", paletteIndex: 3),
        FunFact(text: "Antarctica is the world's largest desert.", symbolName: "snowflake", paletteIndex: 4),
        FunFact(text: "Mount Everest is still rising slowly.", symbolName: "mountain.2.fill", paletteIndex: 5),
        FunFact(text: "The Mariana Trench is deeper than Everest is tall.", symbolName: "arrow.down.circle.fill", paletteIndex: 0),
        FunFact(text: "Earth's core is about as hot as the Sun's surface.", symbolName: "flame.circle.fill", paletteIndex: 1),
        FunFact(text: "Earth is not a perfect sphere.", symbolName: "globe.europe.africa.fill", paletteIndex: 2),
        FunFact(text: "Earth's rotation is gradually slowing down.", symbolName: "timer", paletteIndex: 3),
        FunFact(text: "A year is not exactly 365 days.", symbolName: "calendar", paletteIndex: 4),
        FunFact(text: "Leap seconds help clocks stay aligned with Earth.", symbolName: "clock.badge.checkmark", paletteIndex: 5),
        FunFact(text: "The Sun is white, but Earth's air makes it look yellow.", symbolName: "sun.max.circle.fill", paletteIndex: 0),
        FunFact(text: "Sunlight takes about eight minutes to reach Earth.", symbolName: "sun.max.fill", paletteIndex: 1),
        FunFact(text: "Jupiter has the shortest day of the planets.", symbolName: "circle.grid.cross.fill", paletteIndex: 2),
        FunFact(text: "Mars has the largest volcano in the solar system.", symbolName: "triangle.fill", paletteIndex: 3),
        FunFact(text: "Mercury has ice in shadowed craters.", symbolName: "snowflake", paletteIndex: 4),
        FunFact(text: "Uranus rotates on its side.", symbolName: "rotate.3d", paletteIndex: 5),
        FunFact(text: "Neptune has winds faster than 1,000 mph.", symbolName: "wind", paletteIndex: 0),
        FunFact(text: "Pluto has mountains made of water ice.", symbolName: "mountain.2.fill", paletteIndex: 1),
        FunFact(text: "The asteroid belt is mostly empty space.", symbolName: "circle.dashed", paletteIndex: 2),
        FunFact(text: "A solar eclipse can move across Earth faster than a jet.", symbolName: "circle.lefthalf.filled", paletteIndex: 3),
        FunFact(text: "The Milky Way is on a collision course with Andromeda.", symbolName: "sparkles", paletteIndex: 4),
        FunFact(text: "There are more trees on Earth than stars in the Milky Way.", symbolName: "leaf.fill", paletteIndex: 5),
        FunFact(text: "Some bamboo can grow more than three feet in a day.", symbolName: "leaf.arrow.circlepath", paletteIndex: 0),
        FunFact(text: "Vanilla comes from orchid seed pods.", symbolName: "leaf.fill", paletteIndex: 1),
        FunFact(text: "Pineapples are made of many fused berries.", symbolName: "circle.grid.3x3.fill", paletteIndex: 2),
        FunFact(text: "Peanuts are legumes, not true nuts.", symbolName: "leaf.circle.fill", paletteIndex: 3),
        FunFact(text: "Cashews grow attached to a fruit called a cashew apple.", symbolName: "apple.logo", paletteIndex: 4),
        FunFact(text: "Carrots were not always orange.", symbolName: "paintpalette.fill", paletteIndex: 5),
        FunFact(text: "Coffee beans are seeds from coffee cherries.", symbolName: "cup.and.saucer.fill", paletteIndex: 0),
        FunFact(text: "Chocolate was once used as currency.", symbolName: "seal.fill", paletteIndex: 1),
        FunFact(text: "Popcorn can pop because each kernel has a tiny water pocket.", symbolName: "drop.fill", paletteIndex: 2),
        FunFact(text: "Apples float because they are about 25 percent air.", symbolName: "circle.fill", paletteIndex: 3),
        FunFact(text: "Saffron comes from flower stigmas.", symbolName: "camera.macro", paletteIndex: 4),
        FunFact(text: "Cheese is one of the oldest processed foods.", symbolName: "clock.fill", paletteIndex: 5),
        FunFact(text: "The holes in Swiss cheese are called eyes.", symbolName: "eye.fill", paletteIndex: 0),
        FunFact(text: "Caramelization is sugar chemistry doing delicious theater.", symbolName: "flame.fill", paletteIndex: 1),
        FunFact(text: "A souffle rises because warm air expands.", symbolName: "arrow.up.circle.fill", paletteIndex: 2),
        FunFact(text: "The Maillard reaction creates many toasted flavors.", symbolName: "sparkles", paletteIndex: 3),
        FunFact(text: "Salt can make sweet flavors taste stronger.", symbolName: "drop.triangle.fill", paletteIndex: 4),
        FunFact(text: "Your tongue has thousands of taste buds.", symbolName: "face.smiling.fill", paletteIndex: 5),
        FunFact(text: "Taste and smell team up to create flavor.", symbolName: "wind", paletteIndex: 0),
        FunFact(text: "Your stomach gets a new lining every few days.", symbolName: "arrow.triangle.2.circlepath", paletteIndex: 1),
        FunFact(text: "Your heart beats about 100,000 times a day.", symbolName: "heart.fill", paletteIndex: 2),
        FunFact(text: "Your skin is your largest organ.", symbolName: "hand.raised.fill", paletteIndex: 3),
        FunFact(text: "Your blood vessels could circle Earth more than twice.", symbolName: "waveform.path.ecg", paletteIndex: 4),
        FunFact(text: "Your brain has roughly 86 billion neurons.", symbolName: "brain.head.profile", paletteIndex: 5),
        FunFact(text: "Human teeth are as unique as fingerprints.", symbolName: "touchid", paletteIndex: 0),
        FunFact(text: "Your eye can distinguish millions of colors.", symbolName: "eye.fill", paletteIndex: 1),
        FunFact(text: "You blink around 15 to 20 times per minute.", symbolName: "eye.circle.fill", paletteIndex: 2),
        FunFact(text: "The smallest bone in your body is in your ear.", symbolName: "ear.fill", paletteIndex: 3),
        FunFact(text: "Your lungs contain hundreds of millions of air sacs.", symbolName: "wind", paletteIndex: 4),
        FunFact(text: "Hair is mostly made of keratin.", symbolName: "scissors", paletteIndex: 5),
        FunFact(text: "Dreams can happen in every sleep stage.", symbolName: "moon.stars.fill", paletteIndex: 0),
        FunFact(text: "Your brain cleans up waste while you sleep.", symbolName: "sparkles", paletteIndex: 1),
        FunFact(text: "Laughter can briefly boost heart rate.", symbolName: "heart.circle.fill", paletteIndex: 2),
        FunFact(text: "Music can sync movement across a crowd.", symbolName: "music.note", paletteIndex: 3),
        FunFact(text: "The piano has over 12,000 parts.", symbolName: "pianokeys", paletteIndex: 4),
        FunFact(text: "A standard grand piano has 88 keys.", symbolName: "pianokeys", paletteIndex: 5),
        FunFact(text: "Vinyl records store sound as physical grooves.", symbolName: "record.circle.fill", paletteIndex: 0),
        FunFact(text: "The human voice can make sound without vocal cords touching air.", symbolName: "speaker.wave.3.fill", paletteIndex: 1),
        FunFact(text: "Sound cannot travel through empty space.", symbolName: "speaker.slash.fill", paletteIndex: 2),
        FunFact(text: "A whip crack happens because the tip breaks the sound barrier.", symbolName: "waveform", paletteIndex: 3),
        FunFact(text: "Echoes helped inspire early sonar ideas.", symbolName: "dot.radiowaves.forward", paletteIndex: 4),
        FunFact(text: "Light can circle Earth about seven times in one second.", symbolName: "bolt.fill", paletteIndex: 5),
        FunFact(text: "A rainbow is actually a full circle.", symbolName: "camera.filters", paletteIndex: 0),
        FunFact(text: "The sky looks blue because air scatters short wavelengths.", symbolName: "cloud.fill", paletteIndex: 1),
        FunFact(text: "Glass can be made by lightning striking sand.", symbolName: "bolt.circle.fill", paletteIndex: 2),
        FunFact(text: "Pure gold is so soft you can dent it with a fingernail.", symbolName: "seal.fill", paletteIndex: 3),
        FunFact(text: "Aluminum was once more expensive than gold.", symbolName: "diamond.fill", paletteIndex: 4),
        FunFact(text: "Helium can escape Earth's gravity over time.", symbolName: "balloon.fill", paletteIndex: 5),
        FunFact(text: "Dry ice is frozen carbon dioxide.", symbolName: "snowflake", paletteIndex: 0),
        FunFact(text: "Water expands when it freezes.", symbolName: "drop.fill", paletteIndex: 1),
        FunFact(text: "Mercury is the only metal liquid at room temperature.", symbolName: "thermometer", paletteIndex: 2),
        FunFact(text: "Graphene is only one atom thick.", symbolName: "hexagon.fill", paletteIndex: 3),
        FunFact(text: "Diamonds and pencil graphite are both made of carbon.", symbolName: "pencil.and.scribble", paletteIndex: 4),
        FunFact(text: "A magnet can lose strength when heated enough.", symbolName: "bolt.fill", paletteIndex: 5),
        FunFact(text: "Static electricity can make your hair stand up.", symbolName: "bolt.fill", paletteIndex: 0),
        FunFact(text: "Batteries store energy through chemistry.", symbolName: "battery.100percent", paletteIndex: 1),
        FunFact(text: "LED lights use semiconductors to glow.", symbolName: "lightbulb.fill", paletteIndex: 2),
        FunFact(text: "Lasers can be used to cool atoms.", symbolName: "laser.burst", paletteIndex: 3),
        FunFact(text: "GPS satellites carry atomic clocks.", symbolName: "location.north.circle.fill", paletteIndex: 4),
        FunFact(text: "Atomic clocks can lose less than a second in millions of years.", symbolName: "clock.badge.checkmark", paletteIndex: 5),
        FunFact(text: "The kilogram is now defined using Planck's constant.", symbolName: "scalemass.fill", paletteIndex: 0),
        FunFact(text: "Zero was invented independently in multiple places.", symbolName: "0.circle.fill", paletteIndex: 1),
        FunFact(text: "Pi has been calculated to trillions of digits.", symbolName: "number", paletteIndex: 2),
        FunFact(text: "A googol is a 1 followed by 100 zeros.", symbolName: "number.square.fill", paletteIndex: 3),
        FunFact(text: "The equals sign was invented in 1557.", symbolName: "equal.circle.fill", paletteIndex: 4),
        FunFact(text: "The word hundred comes from an old term meaning ten tens.", symbolName: "textformat", paletteIndex: 5),
        FunFact(text: "Paper can be folded in half more than seven times with enough space.", symbolName: "doc.fill", paletteIndex: 0),
        FunFact(text: "Origami can help engineers design space structures.", symbolName: "paperplane.fill", paletteIndex: 1),
        FunFact(text: "The first known maps are older than writing.", symbolName: "map.fill", paletteIndex: 2),
        FunFact(text: "The compass changed navigation more than almost any tool.", symbolName: "safari.fill", paletteIndex: 3),
        FunFact(text: "The printing press helped books become dramatically cheaper.", symbolName: "book.fill", paletteIndex: 4),
        FunFact(text: "The pencil was invented after a graphite deposit was found.", symbolName: "pencil", paletteIndex: 5),
        FunFact(text: "Erasers became common after rubber reached Europe.", symbolName: "eraser.fill", paletteIndex: 0),
        FunFact(text: "Bubble wrap was first marketed as wallpaper.", symbolName: "circle.grid.3x3.fill", paletteIndex: 1),
        FunFact(text: "Velcro was inspired by burrs sticking to clothing.", symbolName: "link", paletteIndex: 2),
        FunFact(text: "The Slinky was invented by accident.", symbolName: "circle.dashed", paletteIndex: 3),
        FunFact(text: "Post-it Notes came from a glue that was not sticky enough.", symbolName: "note.text", paletteIndex: 4),
        FunFact(text: "The microwave oven was discovered after a melted chocolate bar.", symbolName: "microwave.fill", paletteIndex: 5),
        FunFact(text: "Safety glass was discovered after a flask refused to shatter.", symbolName: "shield.fill", paletteIndex: 0),
        FunFact(text: "Tea bags were popularized by a packaging accident.", symbolName: "cup.and.saucer.fill", paletteIndex: 1),
        FunFact(text: "Cornflakes were invented during a kitchen experiment.", symbolName: "sunrise.fill", paletteIndex: 2),
        FunFact(text: "The first vending machine sold holy water.", symbolName: "shippingbox.fill", paletteIndex: 3),
        FunFact(text: "The first shopping carts appeared in the 1930s.", symbolName: "cart.fill", paletteIndex: 4),
        FunFact(text: "The credit card was inspired by a forgotten wallet.", symbolName: "creditcard.fill", paletteIndex: 5),
        FunFact(text: "The word salary is linked to salt in ancient history.", symbolName: "dollarsign.circle.fill", paletteIndex: 0),
        FunFact(text: "The first paper money appeared in China.", symbolName: "banknote.fill", paletteIndex: 1),
        FunFact(text: "Coins are older than paper money.", symbolName: "centsign.circle.fill", paletteIndex: 2),
        FunFact(text: "The Nobel Prizes began because of Alfred Nobel's will.", symbolName: "medal.fill", paletteIndex: 3),
        FunFact(text: "The Olympic rings represent five inhabited continents.", symbolName: "circle.grid.cross.fill", paletteIndex: 4),
        FunFact(text: "The marathon distance was standardized for the 1908 Olympics.", symbolName: "figure.run", paletteIndex: 5),
        FunFact(text: "Basketball was invented with peach baskets.", symbolName: "basketball.fill", paletteIndex: 0),
        FunFact(text: "Volleyball was first called mintonette.", symbolName: "volleyball.fill", paletteIndex: 1),
        FunFact(text: "Table tennis balls were once made of celluloid.", symbolName: "circle.fill", paletteIndex: 2),
        FunFact(text: "Chess has been played for over 1,000 years.", symbolName: "checkerboard.rectangle", paletteIndex: 3),
        FunFact(text: "The rook in chess was originally linked to a chariot.", symbolName: "crown.fill", paletteIndex: 4),
        FunFact(text: "Playing cards reached Europe in the 1300s.", symbolName: "suit.spade.fill", paletteIndex: 5),
        FunFact(text: "Dice are among the oldest gaming objects found.", symbolName: "die.face.5.fill", paletteIndex: 0),
        FunFact(text: "The Rubik's Cube was invented as a teaching tool.", symbolName: "cube.fill", paletteIndex: 1),
        FunFact(text: "Tetris was created in the Soviet Union.", symbolName: "square.grid.3x3.fill", paletteIndex: 2)
    ]
}
